name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_MANYLINUX_I686_IMAGE: manylinux2014
  JSOC_EMAIL: "jsoc@cadair.com"  # For the example gallery on the dev deps build

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: sunpy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

pr:
  autoCancel: true

stages:
  - stage: FirstPhaseTests
    displayName: Tests
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.8'
        submodules: false
        coverage: codecov
        toxdeps: tox-pypi-filter

        libraries:
          apt:
            - libopenjp2-7
            - graphviz
          brew:
            - openjpeg

        envs:
          - macos: py37
          - windows: py38
          - linux: py38
          - linux: build_docs
            posargs: " "
            pytest: false
